---
version: "2"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    expose:
      - "9000"
      - "8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/portainer/data:/data
      - ${DOCKERDIR}/shared:/shared
    environment:
      - portainer_data:/data

  mariadb:
    image: linuxserver/mariadb:version-110.4.18mariabionic
    container_name: mariadb
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=1000 
      - PGID=1000 
      - MYSQL_USER=iot
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_PASSWORD=123456789
    volumes:
      - ${DOCKERDIR}/mariadb:/config
    ports:
      - 3306:3306/tcp 

  backend:
    image: node:latest
    container_name: backend
    restart: unless-stopped
    command: bash -c "npm install && node index.js"
    volumes:
      - ${API}:/Project
    working_dir: /Project
    expose:
      - 3000

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=iot2.mcmullin.org
      - SUBDOMAINS=www,api,portainer
      - VALIDATION=http
      - EMAIL= matthew@mcmullin.one
      - STAGING=false #optional
    volumes:
      - ${DOCKERDIR}/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped




